### ISSUE TITLE
Fix dependencies

### ISSUE THREAD

**Issue by ghost** [hackhat/cucumberry#6]
Can't you make the fibers dependency optional?
I don't want to install it on windows (too circumstantial), and probably travis does not support it either.

**Comment by ghost** [comment]
```
"fibers": "https://github.com/icenium/node-fibers/tarball/v1.0.5.1",
```

does the trick. You should not use the version number, nobody wants to build especially not on windows, where you need to install python, c++, etc... to do that.

**Comment by ghost** [comment]
I did not manage to install. I give up. It does not recognize .addStep(), because it is not defined. This is because cucumber collects step definitions at first and uses the World only after that. I don't want to dig into the code now I had enough of this. The problem is not with cucumberry, the cucumber-js has very-very-very-@÷ß$Łˇ^°56t,.őßtwhöőp low quality World support. It should be something like this:

``` js
var MyWorld = require("./my.world");

module.exports = MyWorld.extend({
    constructor: function (){
        this.addStep("xxx", /sasdhfrt/, function (){
            ...
        });
        this.addStep("yyy", /swfs/, function (){
            ...
        });
    }
});
```

or with a world.js file which is used globally:

``` js
module.exports = function () {
    this.addStep("xxx", /sasdhfrt/, function () {
        ...
    });
    this.addStep("yyy", /swfs/, function () {
        ...
    });
};
```

Btw I suggest you to allow

``` js
this.addStep(/sasdhfrt/, function () {
    ...
});
```

without unique name (you can always generate it if you want) and make the name optional.

**Comment by ghost** [comment]
The install problem is solved by fibers: https://github.com/laverdet/node-fibers/issues/228 now it is okay.

**Comment by hackhat** [comment]
Sorry for late reply but I didn't had time recently to  look into this issue. I'm happy has been solved by itself.
